### ISSUE TITLE
Incorrect RandomCrop 

### ISSUE THREAD

**Issue by K-Mike** [ternaus/robot-surgery-segmentation#10]
Hi,

I found that RandomCrop works incorrect. You use 

`        h_start = np.random.randint(0, height - self.h)`
        `w_start = np.random.randint(0, width - self.w)
`

but the values will be the same each epoch, better

`h_start = random.randint(0, height - self.h)`
`w_start = random.randint(0, width - self.w)`

P.S. thank you for your code, watching you on Kaggle, cool work!

**Comment by ternaus** [comment]
I replaced all augmentations with https://github.com/albu/albumentations

This problem should not be an issue now.
