### ISSUE TITLE
location of data/models/unet16_binary_20/model_0.pt

### ISSUE THREAD

**Issue by joemcglinchy** [ternaus/robot-surgery-segmentation#11]
Hello, I was looking to run through the demo notebook, but received a FileNotFound error when trying to load `model_path = 'data/models/unet16_binary_20/model_0.pt'`. Does the model need to be trained first to generate these files/directories? Thanks!

**Comment by ternaus** [comment]
You need to download them from https://drive.google.com/open?id=13e0C4fAtJemjewYqxPtQHO6Xggk7lsKe
