### ISSUE TITLE
 UnboundLocalError: local variable 'device_ids' referenced before assignment

### ISSUE THREAD

**Issue by Ivanovicwanheda** [ternaus/robot-surgery-segmentation#15]
When I try the training ( train.py) this error shows up: 
UnboundLocalError: local variable 'device_ids' referenced before assignment
Help please, 
thank you,

**Comment by ShowTsai** [comment]
at line 67:
```python3
if torch.cuda.is_available():
    if args.device_ids:
        device_ids = list(map(int, args.device_ids.split(',')))
    else:
        device_ids = None
    model = nn.DataParallel(model, device_ids=device_ids).cuda()
```
The variable 'device_ids' is assigned here, so I think it needs cuda.
Btw, do you know where to download the dataset?

**Comment by ternaus** [comment]
@ShowTsai is right.

@Ivanovicwanheda It looks like you have some issues with GPU or with drivers. I added check for this in the code in https://github.com/ternaus/robot-surgery-segmentation/pull/17

@ShowTsai I believe asking organizers of the competition will be the best idea.
