### ISSUE TITLE
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 66 and 67 in dimension 2 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:689

### ISSUE THREAD

**Issue by patricegaofei** [ternaus/robot-surgery-segmentation#34]
Hello everyone,
Hope you are all doing well. I have been facing some challenges while trying to run the demo file. In effect, I have read the paper related to this repository and I have noticed that the model was trained with images of 1280 × 1024. When I try running the demo with RGB images of size 1080×1920, it gives the following error.

mask = model(input_image)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "e:\Tools_Seg\robot-surgery-segmentation-master\models.py", line 112, in forward
    dec5 = self.dec5(torch.cat([center, conv5], 1))
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 66 and 67 in dimension 2 at C:\w\1\s\windows\pytorch\aten\src\TH/generic/THTensor.cpp:689
 
However, if I resize my image to a size smaller or equal to that of the images used during training, It works perfectly. 
Please, has anyone faced the same problem? How can I solve it?
Any comments or suggestions would be highy appreciated.

Best regards,

**Comment by alexander-rakhlin** [comment]
Hi!
Both dimensions must be modulo of power of 2. If I recall, 32.

**Comment by patricegaofei** [comment]
Thank you very much for your prompt reply. 

> Hi!
> Both dimensions must be modulo of power of 2. If I recall, 32.

Thank you for your prompt reply.
