### ISSUE TITLE
Rotate transform flips image dimensions

### ISSUE THREAD

**Issue by adizhol** [ternaus/robot-surgery-segmentation#5]
instead of transform.py line 134
            img = cv2.warpAffine(img, mat, (**height, width**),
                                 
need to be
            img = cv2.warpAffine(img, mat, (**width, height**),

because cv2 uses x,y

**Comment by ternaus** [comment]
Thank you.

I replaced all augmentations with https://github.com/albu/albumentations

This problem should not be an issue now.
