### ISSUE TITLE
CUDA: out of memory error in generate_mask.py file

### ISSUE THREAD

**Issue by orion-0** [ternaus/robot-surgery-segmentation#7]
python generate_masks.py --output_path predictions/unet16/binary --model_type UNet16 --problem_type binary --model_path data/models/unet16_binary_20 --fold -1 --batch-size 1

gives error :CUDA: out of memory
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory

Traceback (most recent call last):
  File "generate_masks.py", line 140, in <module>
    predict(model, file_names, args.batch_size, output_path, problem_type=args.problem_type)
  File "generate_masks.py", line 79, in predict
    outputs = model(inputs)
  File "/home/yash/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yash/Desktop/miccai/robot-surgery-segmentation/models.py", line 203, in forward
    dec2 = self.dec2(torch.cat([dec3, conv2], 1))
  File "/home/yash/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yash/Desktop/miccai/robot-surgery-segmentation/models.py", line 49, in forward
    return self.block(x)
  File "/home/yash/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yash/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/yash/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yash/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 690, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

my nvidia-smi output log:-
 NVIDIA-SMI 390.30                 Driver Version: 390.30                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P3    N/A /  N/A |    465MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1444      G   /usr/lib/xorg/Xorg                            28MiB |
|    0      1938      G   /usr/bin/gnome-shell                          49MiB |
|    0      2117      G   /usr/lib/xorg/Xorg                           141MiB |
|    0      2305      G   /usr/bin/gnome-shell                         245MiB

what is being wrong in this??

**Comment by ternaus** [comment]
UNet16 is a very heavy encoder. It just does not fit into the memory of GTX 1050 (I was using 1080 Ti for inference)

you may try:

1.  lighter network 
2. write code that splits an image into tiles, performs inference on them independently and merges predictions back into the original shape. Something like this: https://github.com/ternaus/kaggle_dstl_submission/blob/master/src/extra_functions.py#L243
3. Downscale your images to a smaller size, perform inference and upscale it back to the original shape.
