### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by BUPTAlanMa** [ternaus/robot-surgery-segmentation#8]
I am following your work, and I want give a try.
But, I find The dataset download link was closed In 2017 Robotic Instrument Segmentation Sub-Challenge Although I Registed and Take participate in. The 2018 have not opened Until now.
So,  Would I ask you to give me a link to access the data? Thank you very much. Waiting a reply.

**Comment by Hosseinhashemiir** [comment]
@BUPTAlanMa @ternaus 
The same problem!!!, did you find the way to access the data?

**Comment by ternaus** [comment]
I would believe that contacting organizers will be the best option.
